name = "d1-id"
main = "src/index.ts"
compatibility_date = "2022-06-17"
route = "id.uuid.rocks/*"
usage_model = "unbound"

[[ d1_databases ]]
binding = "D1"
database_name = "ids-fast"
database_id = "ac85e7be-6beb-4bb2-be2f-b431be12ed40"

# [[unsafe.bindings]]
# name = "D1"
# type = "cfsql"
# database = "ids"
